// <auto-generated />
namespace CustomerTracker.Web.Angular.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initial_create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initial_create));
        
        string IMigrationMetadata.Id
        {
            get { return "201411070930313_initial_create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
