// <auto-generated />
namespace CustomerTracker.Web.Angular.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class create_index : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_index));
        
        string IMigrationMetadata.Id
        {
            get { return "201411070931258_create_index"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
