// <auto-generated />
namespace CustomerTracker.Web.Angular.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update_datamaster : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_datamaster));
        
        string IMigrationMetadata.Id
        {
            get { return "201411211221533_update_datamaster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
