// <auto-generated />
namespace CustomerTracker.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_customdata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_customdata));
        
        string IMigrationMetadata.Id
        {
            get { return "201405302332180_added_customdata"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
