// <auto-generated />
namespace CustomerTracker.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class added_applicationservice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_applicationservice));
        
        string IMigrationMetadata.Id
        {
            get { return "201406140926302_added_applicationservice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
