// <auto-generated />
namespace CustomerTracker.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dummy_data : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dummy_data));
        
        string IMigrationMetadata.Id
        {
            get { return "201405191813410_dummy_data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
