// <auto-generated />
namespace CustomerTracker.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class create_index_on_remotemachine : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(create_index_on_remotemachine));
        
        string IMigrationMetadata.Id
        {
            get { return "201406141254175_create_index_on_remotemachine"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
