// <auto-generated />
namespace CustomerTracker.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class modifty_Datamaster : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifty_Datamaster));
        
        string IMigrationMetadata.Id
        {
            get { return "201405302334339_modifty_Datamaster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
