// <auto-generated />
namespace CustomerTracker.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class add_soluiton_and_trouble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_soluiton_and_trouble));
        
        string IMigrationMetadata.Id
        {
            get { return "201406071600105_add_soluiton_and_trouble"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
