// <auto-generated />
namespace CustomerTracker.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class update_applicationservice_name : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_applicationservice_name));
        
        string IMigrationMetadata.Id
        {
            get { return "201406141248326_update_applicationservice_name"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
