// <auto-generated />
namespace CustomerTracker.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class logoimagename : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(logoimagename));
        
        string IMigrationMetadata.Id
        {
            get { return "201405310933518_logoimagename"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
